package io.github.aasaru.drools.section03.step2
 
import io.github.aasaru.drools.domain.Passport;
import java.time.LocalDate;

rule "Valid passport"
  dialect "mvel"
  when
	Passport( !isExpired(), unusedVisaPages > 0 )
  then
	System.out.println( "This passport is CORRECT" );
end

// Fill in the when and then parts for these rules
rule "Expired passport"
  dialect "mvel"
  when

  then

end

rule "Full passport"
  dialect "mvel"
  when

  then

end

