package io.github.aasaru.drools.section03.step4
 
import io.github.aasaru.drools.domain.Passport;
import io.github.aasaru.drools.domain.Validation;
import java.time.LocalDate

//set Validation of passport in first rule to passed, and in other two rules
//to failed
rule "Valid passport"
  dialect "mvel"
  when
	$passport: Passport( !isExpired(), $unusedPages: unusedVisaPages > 0 )
  then
	System.out.println( $passport + " is CORRECT. It has " + $unusedPages + " pages free." );

end

rule "Expired passport"
  dialect "mvel"
  when
	$passport: Passport( isExpired() )
  then
	System.out.println( $passport + " is INVALID because it is expired" );

end

rule "Full passport"
  dialect "mvel"
  when
	$passport: Passport( unusedVisaPages == 0 )
  then
	System.out.println( $passport + " is INVALID because it has no space for visa" );

end
