package io.github.aasaru.drools.section03.step3
 
import io.github.aasaru.drools.domain.Passport;
import java.time.LocalDate;

rule "Valid passport"
  dialect "mvel"
  when
	$passport: Passport( !isExpired(), $unusedPages: unusedVisaPages > 0 )
  then
	System.out.println( $passport + " is CORRECT. It has " + $unusedPages + " pages free." );
end
/* Save the passport object in a variable $passport and print
a matching message using the variable.*/

rule "Expired passport"
  dialect "mvel"
  when

  then

end

rule "Full passport"
  dialect "mvel"
  when

  then

end
